import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="bg-bg">
        {children}</body>
    </html>
  );
}
